/**
 * DUNDAO 展台风格 Token 库
 * 消费方式:
 * 1. 在 useTheme.js 或入口文件中引入 THEMES
 * 2. applyTheme(theme) 会将 tokens 注入为 CSS Variables (--color-stage 等)
 * 3. 同时会注入 data-surface, data-split, data-card-aspect, data-type-scale 到 <html>
 */

export const THEMES = [
  {
    id: 'healing-warmth',
    name: '暖色治愈',
    tagline: '默认风格 · 温暖的余烬与呼吸感',
    surface: 'dark',
    tokens: {
      '--color-stage': '#0c0a09',
      '--color-panel': '#1c1917',
      '--color-ink': '#f5f5f4',
      '--color-text': '#fafaf9',
      '--color-text-muted': '#e7e5e4',
      '--color-warmth': '#fb923c',
      '--color-ember': '#f97316',
      '--color-kiss': '#f43f5e',
      '--color-hintA': '#fbbf24',
      '--color-hintB': '#38bdf8',
      '--color-hintC': '#4ade80',
      '--font-sans': '"Inter", "PingFang SC", sans-serif',
      '--radius-card': '24px',
      '--radius-pill': '999px',
      '--shadow-card': '0 10px 30px -10px rgba(0,0,0,0.5)',
      '--shadow-soft': '0 4px 12px rgba(0,0,0,0.2)',
      '--card-border': '1px solid rgba(255,255,255,0.08)',
      '--surface-glow': 'radial-gradient(ellipse 900px 400px at 50% 110%, rgba(249,115,22,0.12), transparent 70%), #0c0a09',
    },
    layout: { split_ratio: '7-5', card_aspect: 'portrait', type_scale: 'normal' }
  },
  {
    id: 'cyber-neon',
    name: '赛博霓虹',
    tagline: '未来主义 · 高饱和度电子梦境',
    surface: 'dark',
    tokens: {
      '--color-stage': '#020617',
      '--color-panel': '#0f172a',
      '--color-ink': '#f8fafc',
      '--color-text': '#e2e8f0',
      '--color-text-muted': '#cbd5e1',
      '--color-warmth': '#22d3ee',
      '--color-ember': '#818cf8',
      '--color-kiss': '#f472b6',
      '--color-hintA': '#facc15',
      '--color-hintB': '#2dd4bf',
      '--color-hintC': '#fb7185',
      '--font-sans': '"JetBrains Mono", "PingFang SC", monospace',
      '--radius-card': '4px',
      '--radius-pill': '2px',
      '--shadow-card': '0 0 20px rgba(34,211,238,0.2)',
      '--shadow-soft': '0 0 10px rgba(244,114,182,0.1)',
      '--card-border': '1px solid #1e293b',
      '--surface-glow': 'linear-gradient(135deg, rgba(34,211,238,0.1), rgba(244,114,182,0.1))',
    },
    layout: { split_ratio: '6-6', card_aspect: 'square', type_scale: 'compact' }
  },
  {
    id: 'minimal-magazine',
    name: '极简杂志',
    tagline: '纸本触感 · 呼吸感与留白的艺术',
    surface: 'light',
    tokens: {
      '--color-stage': '#f8f7f4',
      '--color-panel': '#ffffff',
      '--color-ink': '#1a1a1a',
      '--color-text': '#262626',
      '--color-text-muted': '#525252',
      '--color-warmth': '#404040',
      '--color-ember': '#525252',
      '--color-kiss': '#a3a3a3',
      '--color-hintA': '#d4d4d4',
      '--color-hintB': '#e5e5e5',
      '--color-hintC': '#fafafa',
      '--font-sans': '"Noto Serif SC", "Source Han Serif SC", serif',
      '--radius-card': '0px',
      '--radius-pill': '0px',
      '--shadow-card': 'none',
      '--shadow-soft': 'none',
      '--card-border': '1px solid #e5e5e5',
      '--surface-glow': '#ffffff',
    },
    layout: { split_ratio: '8-4', card_aspect: 'portrait', type_scale: 'airy' }
  },
  {
    id: 'soft-clay',
    name: '软糖粘土',
    tagline: '微光拟态 · 柔润的触手可及',
    surface: 'light',
    tokens: {
      '--color-stage': '#f0f4f8',
      '--color-panel': '#f8fafc',
      '--color-ink': '#334155',
      '--color-text': '#475569',
      '--color-text-muted': '#94a3b8',
      '--color-warmth': '#fb7185',
      '--color-ember': '#fda4af',
      '--color-kiss': '#fecdd3',
      '--color-hintA': '#bfdbfe',
      '--color-hintB': '#bbf7d0',
      '--color-hintC': '#fef08a',
      '--font-sans': '"Inter", sans-serif',
      '--radius-card': '40px',
      '--radius-pill': '999px',
      '--shadow-card': '20px 20px 60px #d1d9e6, -20px -20px 60px #ffffff',
      '--shadow-soft': 'inset 6px 6px 12px rgba(0,0,0,0.05), inset -6px -6px 12px rgba(255,255,255,0.8)',
      '--card-border': '2px solid #ffffff',
      '--surface-glow': 'linear-gradient(145deg, #ffffff, #e6e9ef)',
    },
    layout: { split_ratio: '7-5', card_aspect: 'square', type_scale: 'normal' }
  },
  {
    id: 'frosted-glass',
    name: '迷雾玻璃',
    tagline: '磨砂质感 · 虚实交织的纵深',
    surface: 'dark',
    tokens: {
      '--color-stage': '#111827',
      '--color-panel': 'rgba(31, 41, 55, 0.4)',
      '--color-ink': '#f9fafb',
      '--color-text': '#f3f4f6',
      '--color-text-muted': '#e5e7eb',
      '--color-warmth': '#60a5fa',
      '--color-ember': '#3b82f6',
      '--color-kiss': '#2563eb',
      '--color-hintA': '#8b5cf6',
      '--color-hintB': '#ec4899',
      '--color-hintC': '#10b981',
      '--font-sans': '"Inter", sans-serif',
      '--radius-card': '32px',
      '--radius-pill': '999px',
      '--shadow-card': '0 8px 32px 0 rgba(0, 0, 0, 0.37)',
      '--shadow-soft': '0 2px 10px rgba(255,255,255,0.05)',
      '--card-border': '1px solid rgba(255, 255, 255, 0.12)',
      '--surface-glow': 'radial-gradient(at 0% 0%, rgba(59,130,246,0.1), transparent)',
    },
    layout: { split_ratio: '7-5', card_aspect: 'portrait', type_scale: 'normal' }
  },
  {
    id: 'neo-brutalism',
    name: '新野兽派',
    tagline: '高反差 · 粗砺且自信的表达',
    surface: 'light',
    tokens: {
      '--color-stage': '#ffde00',
      '--color-panel': '#ffffff',
      '--color-ink': '#000000',
      '--color-text': '#000000',
      '--color-text-muted': '#000000',
      '--color-warmth': '#ff0055',
      '--color-ember': '#00ff00',
      '--color-kiss': '#0055ff',
      '--color-hintA': '#ffffff',
      '--color-hintB': '#000000',
      '--color-hintC': '#ffde00',
      '--font-sans': '"Archivo Black", "Inter", sans-serif',
      '--radius-card': '0px',
      '--radius-pill': '0px',
      '--shadow-card': '12px 12px 0px #000000',
      '--shadow-soft': '4px 4px 0px #000000',
      '--card-border': '4px solid #000000',
      '--surface-glow': '#ffffff',
    },
    layout: { split_ratio: '5-7', card_aspect: 'landscape', type_scale: 'airy' }
  },
  {
    id: 'pixel-y2k',
    name: '像素复古',
    tagline: '千禧美学 · 8-bit 的数字乡愁',
    surface: 'light',
    tokens: {
      '--color-stage': '#e0f2fe',
      '--color-panel': '#ffffff',
      '--color-ink': '#0c4a6e',
      '--color-text': '#075985',
      '--color-text-muted': '#0ea5e9',
      '--color-warmth': '#f472b6',
      '--color-ember': '#fb7185',
      '--color-kiss': '#818cf8',
      '--color-hintA': '#2dd4bf',
      '--color-hintB': '#fbbf24',
      '--color-hintC': '#f87171',
      '--font-sans': '"Press Start 2P", "JetBrains Mono", monospace',
      '--radius-card': '8px',
      '--radius-pill': '4px',
      '--shadow-card': '4px 4px 0px #0ea5e9, 8px 8px 0px #e0f2fe',
      '--shadow-soft': '2px 2px 0px #0ea5e9',
      '--card-border': '3px solid #0ea5e9',
      '--surface-glow': 'repeating-linear-gradient(45deg, transparent, transparent 10px, rgba(14,165,233,0.05) 10px, rgba(14,165,233,0.05) 20px)',
    },
    layout: { split_ratio: '6-6', card_aspect: 'square', type_scale: 'compact' }
  },
  {
    id: 'notebook-paper',
    name: '手记纸本',
    tagline: '触感记录 · 每一笔都有温度',
    surface: 'light',
    tokens: {
      '--color-stage': '#fefce8',
      '--color-panel': '#fff',
      '--color-ink': '#1e293b',
      '--color-text': '#334155',
      '--color-text-muted': '#94a3b8',
      '--color-warmth': '#ea580c',
      '--color-ember': '#c2410c',
      '--color-kiss': '#9a3412',
      '--color-hintA': '#ca8a04',
      '--color-hintB': '#16a34a',
      '--color-hintC': '#2563eb',
      '--font-sans': '"Caveat", "Kaiti", serif',
      '--radius-card': '4px',
      '--radius-pill': '999px',
      '--shadow-card': '2px 2px 10px rgba(0,0,0,0.05)',
      '--shadow-soft': '1px 1px 4px rgba(0,0,0,0.02)',
      '--card-border': '1px solid #e2e8f0',
      '--surface-glow': 'linear-gradient(rgba(0,0,0,0.02) 1px, transparent 1px) 0 0 / 100% 24px',
    },
    layout: { split_ratio: '7-5', card_aspect: 'portrait', type_scale: 'normal' }
  },
  {
    id: 'forest-nature',
    name: '森林自然',
    tagline: '生机勃勃 · 沉浸于旷野的深呼吸',
    surface: 'dark',
    tokens: {
      '--color-stage': '#052e16',
      '--color-panel': '#064e3b',
      '--color-ink': '#ecfdf5',
      '--color-text': '#d1fae5',
      '--color-text-muted': '#bef264',
      '--color-warmth': '#bef264',
      '--color-ember': '#84cc16',
      '--color-kiss': '#facc15',
      '--color-hintA': '#10b981',
      '--color-hintB': '#0ea5e9',
      '--color-hintC': '#fb923c',
      '--font-sans': '"Inter", sans-serif',
      '--radius-card': '48px',
      '--radius-pill': '999px',
      '--shadow-card': '0 20px 40px rgba(0,0,0,0.4)',
      '--shadow-soft': '0 4px 12px rgba(0,0,0,0.2)',
      '--card-border': '1px solid rgba(190,242,100,0.1)',
      '--surface-glow': 'radial-gradient(circle at 100% 100%, rgba(190,242,100,0.1), transparent)',
    },
    layout: { split_ratio: '8-4', card_aspect: 'portrait', type_scale: 'normal' }
  },
  {
    id: 'hk-neon',
    name: '霓虹港风',
    tagline: '午夜街头 · 斑斓的电影感叙事',
    surface: 'dark',
    tokens: {
      '--color-stage': '#000000',
      '--color-panel': '#0a0a0a',
      '--color-ink': '#ffffff',
      '--color-text': '#f5f5f5',
      '--color-text-muted': '#d4d4d4',
      '--color-warmth': '#ef4444',
      '--color-ember': '#f59e0b',
      '--color-kiss': '#dc2626',
      '--color-hintA': '#fbbf24',
      '--color-hintB': '#10b981',
      '--color-hintC': '#3b82f6',
      '--font-sans': '"Source Han Sans SC", "PingFang SC", sans-serif',
      '--radius-card': '2px',
      '--radius-pill': '0px',
      '--shadow-card': '0 0 15px rgba(239,68,68,0.3)',
      '--shadow-soft': '0 0 5px rgba(245,158,11,0.2)',
      '--card-border': '1px solid #262626',
      '--surface-glow': 'linear-gradient(to bottom, rgba(239,68,68,0.05), transparent)',
    },
    layout: { split_ratio: '7-5', card_aspect: 'landscape', type_scale: 'normal' }
  },
  {
    id: 'zen-ink',
    name: '水墨禅意',
    tagline: '大道至简 · 留白里的万象乾坤',
    surface: 'light',
    tokens: {
      '--color-stage': '#ffffff',
      '--color-panel': '#fafafa',
      '--color-ink': '#000000',
      '--color-text': '#171717',
      '--color-text-muted': '#525252',
      '--color-warmth': '#404040',
      '--color-ember': '#525252',
      '--color-kiss': '#262626',
      '--color-hintA': '#a3a3a3',
      '--color-hintB': '#d4d4d4',
      '--color-hintC': '#e5e5e5',
      '--font-sans': '"Noto Serif SC", serif',
      '--radius-card': '0px',
      '--radius-pill': '0px',
      '--shadow-card': 'none',
      '--shadow-soft': 'none',
      '--card-border': 'none',
      '--surface-glow': 'linear-gradient(to right, #f5f5f5, #ffffff)',
    },
    layout: { split_ratio: '6-6', card_aspect: 'portrait', type_scale: 'airy' }
  },
  {
    id: 'scrapbook',
    name: '剪贴簿',
    tagline: '拼贴记忆 · 灵感的混沌与秩序',
    surface: 'light',
    tokens: {
      '--color-stage': '#f3f4f6',
      '--color-panel': '#ffffff',
      '--color-ink': '#111827',
      '--color-text': '#374151',
      '--color-text-muted': '#6b7280',
      '--color-warmth': '#8b5cf6',
      '--color-ember': '#ec4899',
      '--color-kiss': '#f59e0b',
      '--color-hintA': '#10b981',
      '--color-hintB': '#3b82f6',
      '--color-hintC': '#ef4444',
      '--font-sans': '"Inter", sans-serif',
      '--radius-card': '12px',
      '--radius-pill': '999px',
      '--shadow-card': '5px 5px 0px rgba(0,0,0,0.1)',
      '--shadow-soft': '2px 2px 0px rgba(0,0,0,0.05)',
      '--card-border': '2px dashed #d1d5db',
      '--surface-glow': '#ffffff',
    },
    layout: { split_ratio: '5-7', card_aspect: 'square', type_scale: 'normal' }
  }
];
